redis:
  image: redis:3.0.2
  restart: always
  ports:
    - "6379"
registryv2:
  restart: always
  image: registry:2.0.1
  ports:
    - "5000"
  environment:
    - REGISTRY_STORAGE=s3
    - REGISTRY_STORAGE_S3_ACCESSKEY=replace-me
    - REGISTRY_STORAGE_S3_SECRETKEY=replace-me
    - REGISTRY_STORAGE_S3_BUCKET=replace-me
    - REGISTRY_STORAGE_S3_REGION=us-west-2
    - REGISTRY_ROOTDIRECTORY=/registry
    - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis
    - REGISTRY_HTTP_ADDR=:5000
    - REGISTRY_REDIS_ADDR=redis:6379
nginx:
  image: nginx:1.9
  ports:
    - "5000:5000"
  links:
    - registryv2:registryv2
  volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/registry.conf:/etc/nginx/conf.d/registry.conf
    - $PWD/docker-registry-v2.conf:/etc/nginx/docker-registry-v2.conf
