redis:
  image: redis:3.0.2
  restart: always
  ports:
    - "6379"
  labels:
    com.finishfirstsoftware.application.name: "redis"
    com.finishfirstsoftware.application.version: "3.0.2"
registryv2:
  image: registry:2.0.1
  restart: always
  ports:
    - "5000"
  environment:
    - REGISTRY_STORAGE=s3
    - REGISTRY_STORAGE_S3_REGION=us-west-2
    - REGISTRY_ROOTDIRECTORY=/registry
    - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis
    - REGISTRY_HTTP_ADDR=:5000
    - REGISTRY_REDIS_ADDR=redis:6379
  env_file:
    - .env.registry
  links:
    - redis
  labels:
    com.finishfirstsoftware.application.name: "registry"
    com.finishfirstsoftware.application.version: "v2"
nginx:
  image: nginx:1.9
  restart: always
  ports:
    - "5000:5000"
  links:
    - registryv2
  volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/registry.conf:/etc/nginx/conf.d/registry.conf
    - $PWD/docker-registry-v2.conf:/etc/nginx/docker-registry-v2.conf
  labels:
    com.finishfirstsoftware.application.name: "registry-proxy"
    com.finishfirstsoftware.application.version: "1.9"
